### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by dillibabukadati** [danielheyman/social-exchange-script#3]
i'm getting error:

Parse error: syntax error, unexpected end of file in **/storage/ssd4/318/2123318/public_html/config.php** on **line 29**
i tried all versions of php but didn't work please help me

**Comment by z3r0d4rkn3ss** [comment]
i have a working version....

**Comment by z3r0d4rkn3ss** [comment]
make sure these fields are correct
`$host		=	""; // your mysql server address
$user		=	""; // your mysql username
$pass		=	""; // your mysql password
$tablename	=	""; // your mysql table`

if localhost dont work try the actual hoster sql address

**Comment by LlopBlanc** [comment]
I have the same problem that the other user Can  you help me, please.

**Comment by z3r0d4rkn3ss** [comment]
the mysql should work BEFORE php version 5.5, after this you need to change config and all files from mysql > mysqli, if your running php 7.0

https://www.w3schools.com/php/php_ref_mysqli.asp

**Comment by LlopBlanc** [comment]
I tried, with previous versions. but I still have the same error

**Comment by MatthewMelvinBelcher** [comment]
show me image of error

**Comment by LlopBlanc** [comment]
Parse error: syntax error, unexpected $end in /storage/ssd2/831/3999831/public_html/config.php on line 29

**Comment by MatthewMelvinBelcher** [comment]
`<?php
error_reporting(E_ALL);
ini_set('display_errors', '1');

$host		=	""; // your mysql server address
$user		=	""; // your mysql username
$pass		=	""; // your mysql password
$tablename	=	""; // your mysql table

session_start();
$data = null;
if(!(@mysql_connect("$host","$user","$pass") && @mysql_select_db("$tablename"))) {
    ?>
    <html>
    MSQL ERROR
    <?
    exit;
}

include_once 'functions.php';
require_once "includes/pluggable.php";
foreach( glob("plugins/*/index.php")  as $plugin) {  
require_once($plugin);  
}  

hook_action('initialize');

$site = mysql_fetch_object(mysql_query("SELECT * FROM settings"));
?>`

**Comment by LlopBlanc** [comment]
I have the same

**Comment by LlopBlanc** [comment]
any solution ??

**Comment by danielheyman** [comment]
Thanks for helping out @MatthewMelvinBelcher. I haven't maintained/ran this codebase in years

**Comment by z3r0d4rkn3ss** [comment]
No problem @danielheyman, im using this project as my foundation in making some new cool plugins too :) any money made on site will go to charity, granja solidaria santiago 1:27 who help orphans and widows.
if you can help out with issues on /plugins/yt/  & /plugins/surf/ that would be a blessing :)
![image](https://user-images.githubusercontent.com/31696563/35818848-025156dc-0a99-11e8-96a5-77996dbe0454.png)
