### ISSUE TITLE
Surf Error and Youtube Error

### ISSUE THREAD

**Issue by z3r0d4rkn3ss** [danielheyman/social-exchange-script#4]
After count down user doesnt get credited on surf, youtube count down and credit doesnt work.

**Comment by z3r0d4rkn3ss** [comment]
also error on surf next button.... `
<button onclick="javascript:refreshpage()" style="display:none; margin-left:20px;" id="<?php echo $site2->id; ?>">Next</button>`

**Comment by ARMADAIX** [comment]
Hi. Where did You get the source code of this script?

**Comment by z3r0d4rkn3ss** [comment]
I built the extra parts needed

**Comment by ARMADAIX** [comment]
So this is your development? - http://shareyt.com

**Comment by z3r0d4rkn3ss** [comment]
no this is not my project... i downloaded it and added my own scripts and
had to do major edits for it to work.

**Comment by z3r0d4rkn3ss** [comment]
this is the original script for social exchange

**Comment by ARMADAIX** [comment]
Have you solved the problem with the timer on YouTube???

**Comment by z3r0d4rkn3ss** [comment]
Yes, I have it working... Tracks video then credits then moves to next
video.

**Comment by ARMADAIX** [comment]
Can you give the PHP code from YouTube?

**Comment by z3r0d4rkn3ss** [comment]
You would like my youtube code?

**Comment by ARMADAIX** [comment]
Yes.

**Comment by ARMADAIX** [comment]
gosha.goshan2015@yandex.ru

**Comment by ARMADAIX** [comment]
E-mail Up

**Comment by z3r0d4rkn3ss** [comment]
Ok, give me hour and I'll submit pull request and drop code into this
comment... I need to go into FTP and grab it.

**Comment by ARMADAIX** [comment]
Ok

**Comment by z3r0d4rkn3ss** [comment]
Can find working code here... https://github.com/MatthewMelvinBelcher/social-exchange-script/blob/MatthewMelvinBelcher-patch-1/plugins/yt/xchange.php

**Comment by ARMADAIX** [comment]
Похожий скрипт но не работает на YouTube https://techno-co.ru/besplatno/other_cms/other/179-dvizhok-raskrutki-powerful-exchange-system-v20-nulled.html

**Comment by ARMADAIX** [comment]
A similar script but is not working on YouTube https://techno-co.ru/besplatno/other_cms/other/179-dvizhok-raskrutki-powerful-exchange-system-v20-nulled.html

**Comment by z3r0d4rkn3ss** [comment]
my code works... i have my site up and running using the basic foundation of this script :)

**Comment by ARMADAIX** [comment]
GOOD! WORK YouTube!

**Comment by ARMADAIX** [comment]
I want a similar site - https://smofast.com

**Comment by z3r0d4rkn3ss** [comment]
if you pay me all build it within seven working days :)

**Comment by ARMADAIX** [comment]
$-?

**Comment by z3r0d4rkn3ss** [comment]
Hello there,

I just signed the petition "Theresa May MP: Hold Voting Online, on .Gov
websites" and wanted to see if you could help by adding your name.

Our goal is to reach 100 signatures and we need more support. You can read
more and sign the petition here:

https://chn.ge/2PoVduE

Thanks!
MATTHEW
